### ISSUE TITLE
Sample solution project "Greeter" is missing dependency DIDComm.Messaging.gRPC  

### ISSUE THREAD

**Issue by adrianwium** [trinsic-id/okapi#169]
Cloned the repo https://github.com/trinsic-id/okapi

Opened "Greeter" sample solution

Dependency DIDComm.Messaging.gRPC  is missing

![Okapi](https://user-images.githubusercontent.com/82496337/134013381-5cb143d8-9378-4c51-8f06-a696e08bced9.png)

**Comment by tmarkovski** [comment]
Thanks for reporting this @adrianwium . It seems that sample is pointing to the old library projects, that we have since changed. I'll get that fixed and post update here.

**Comment by fundthmcalculus** [comment]
@tmarkovski aren't we moving all the samples to the trinsic-samples repository?

**Comment by adrianwium** [comment]
Thank you


With kind regards,



Adrian Wium
Partner / Director

[cid:BiggerLogo(Square240x240)_f6b79b25-7da4-4680-a787-28ad84ff9ce1.png]<http://www.tanoinsights.com/>

TANOInsights (Pty) LTD
+27 (82) 926-0618 | ***@***.***<mailto:%7BE-mail%7D>
766 Besembiesie Rd, Montana Park, Pretoria, South Africa
TANOInsights<http://www.tanoinsights.com/>

[cid:SocialLink_Linkedin_32x32_c95b44ad-6889-49b1-a677-0b5a8500be3e.png]<https://www.linkedin.com/in/Adrian-Wium-0829260618>


This message contains confidential information and is intended only for the individual(s) addressed in the message. If you are not the named addressee, you should not disseminate, distribute, or copy this e-mail. If you are not the intended recipient, you are notified that disclosing, distributing, or copying this e-mail is strictly prohibited.

**Comment by tmarkovski** [comment]
> @tmarkovski aren't we moving all the samples to the trinsic-samples repository?

Correct. `okapi-examples` repo
