### ISSUE TITLE
winget native binary deploy

### ISSUE THREAD

**Issue by fundthmcalculus** [trinsic-id/okapi#288]
Support deploying the native okapi binaries via winget and a native MSIX installer.
- [x] WIX installer https://github.com/trinsic-id/okapi/pull/290
- [x] Winget package manifest https://github.com/microsoft/winget-pkgs/pull/36768
- [x] Winget Trinsic CLI https://github.com/microsoft/winget-pkgs/pull/36769

**Comment by tmarkovski** [comment]
`cargo-wix` should make this a breeze - https://github.com/volks73/cargo-wix
We should publish this as release artifact.

This link may help with the initial manifest creation, though that doesn't seem too complicated - https://marcinotorowski.com/2020/07/08/publishing-to-winget-with-msix-hero/

**Comment by fundthmcalculus** [comment]
Yup, I'd found those links, set this aside while I was prepping the android demo.

**Comment by fundthmcalculus** [comment]
Once we have a released `.msi`, I will create the PR for `winget install` here:
https://github.com/trinsic-id/winget-pkgs/tree/master
