### ISSUE TITLE
Build protobuf generated files on github actions

### ISSUE THREAD

**Issue by fundthmcalculus** [trinsic-id/okapi#324]
This will reduce complexity for us, as well as provide better versioning support.
- [x] Ensure list of all required plugins
- [x] README.md information for discovery
- [x] Python better proto utilize plugin form
- [x] Python build script download required plugins maybe?
- [x] Create github action to perform this automatically - still require manual merge in?
- [ ] ~buf.build (once it supports what we need)~

**Comment by tmarkovski** [comment]
Big supporter of this! Even if we can make this work for some languages, it'll be worth it.

**Comment by fundthmcalculus** [comment]
Yup, I'm just wrapping my head around the best way to make my personal process more repeatable. 👍 Whether that's on buf.build initially or not is irrelevant. I want the protobuf generator to be ephemeral and stateless if possible.

**Comment by fundthmcalculus** [comment]
Digging into the buf.build process indicates that it's not yet ready for prime time. That being said, we should set up a github action that can generate all the protobuf files.

We should also check the generated files into the repository to ensure consistency, and for some languages, they require manual (via my Python script) tweaking.

**Comment by tmarkovski** [comment]
Seems like a lot of overhead. Can we decide this on a per language basis? The proto files are still the source of truth, and this should be enough to guarantee interop with the native library. .NET generates this files on the fly, it would be a lot of extra work to check them in. Other languages do this differently - I suggest not to try and centralize it, but it keep localized.

**Comment by fundthmcalculus** [comment]
Agreed on per language. That being said, every language except dotnet has them checked in.

**Comment by tmarkovski** [comment]
.NET and Wasm (both Node and Browser) don't have them checked in, too.

**Comment by fundthmcalculus** [comment]
Moving to 2022Q2 due to limitations on the buf.build system. Github actions protobuf build support already exists.
