### ISSUE TITLE
Add required BLAKE3 hashing support to okapi

### ISSUE THREAD

**Issue by fundthmcalculus** [trinsic-id/okapi#345]
### Requirements
1. Expose function call: `hash_blake3(ByteBuffer request, ByteBuffer* response, ExternError* error)`
2. Update okapi language bindings to support this call (will be a separate sdk change request ticket)
### Reasoning
We want a consistent BLAKE3 hashing experience across languages, compiled and running at processor native speeds. Having the requisite BLAKE3 algorithm embedded into Okapi will help us to accomplish this objective. In addition, it will reduce issues with WASM and some other language bindings having weird installation procedures.
### Discussion questions
1. Will there be other hash format requirements?
2. Should there be only one function call `hash_algo()`, with a parameter for the hashing algorithm to use?

**Comment by tmarkovski** [comment]
Suggestion:
- Create new namespace `okapi.hashing.v1` with `hashing.proto`, or `okapi.crypto.v1`, no strong preference
- Expose both hash and keyed hash functions
- Use naming such that it allows us to extend with other hashing functionalities

**Comment by fundthmcalculus** [comment]
> Suggestion:
> 
> * Create new namespace `okapi.hashing.v1` with `hashing.proto`, or `okapi.crypto.v1`, no strong preference
> * Expose both hash and keyed hash functions
> * Use naming such that it allows us to extend with other hashing functionalities

* `okapi.hashing.v1` it is. I think that's more general, in the event that we have a non-crypto hash for some reason.
* `hash_blake3(ByteBuffer input, ByteBuffer output, ExternError)` and `hash_blake3_keyed(ByteBuffer input, ByteBuffer output, char* key, ExternError)` sound good?
* General form will be `hash_[algorithm][_keyed?]()` `_keyed` form will add a key parameter of some type, see above.

**Comment by fundthmcalculus** [comment]
> > Do we want to return the algorithm as well?
> 
> It seems like a good idea to me. It can help callers be mindful with typing/sizing since the hashes will vary in size. _If_ they are optimizing at that level and _if_ we care that they might fall into pitfalls of defaults (e.g. a part of code might not know the request type it just sent), it would be useful.

Agreed, I'll return it then. The other question is how to handle hash-specific options? Eg. blake3 hash size. (return 32? 64? 127? other?). I don't want to make it super complicated. Maybe we return the entire hash, and let the caller truncate it (keeps sdk oberon metadata size under control).

**Comment by tmarkovski** [comment]
If the hash request carries all input, there's no need for two separate API calls. Using a single entry `hash(HashRequest, out HashResponse, out Error) -> int` is enough.

**Comment by fundthmcalculus** [comment]
> If the hash request carries all input, there's no need for two separate API calls. Using a single entry `hash(HashRequest, out HashResponse, out Error) -> int` is enough.
> 
> Edit: Looking at Blake3, it seems it supports three functions, `hash`, `keyed_hash` and `derive_key`. I'd say this makes it complex enough to make it a candidate for it's own API calls, and not bundle them into one.

Agreed that those should be separate. But are there other hash operations that require functions besides those? Maybe we throw a `NotImplementedError` if you call `keyed_hash` with for `MD5` (for example). That, or we just expose each hash function as its own FFI call, and live with the plethora of functions that might ensue if we support other hashing algorithms.

I kind of lean towards keeping the FFI interface flat, so expose each type of call as a separate call, rather than a bunch of `if` logic inside the function. Eg, let's do this:
`hash_blake3`, `keyed_hash_blake3`, `derive_key_blake3`, -AND-
`hash_md5` (I know it's insecure, this is an example)
`hash_blake2`, `keyed_hash_blake2`, ...

**Comment by tmarkovski** [comment]
Yeah, I'm leaning towards a separate API. I would use the type prefix at the start `blake3_hash`, `blake3_keyed_hash`, `blake3_derive_key` and their message types accordingly `Blake3HashRequst`, etc.

This, combined with the namespace, makes it unambigous - `okapi/hashing/v1/blake3_hash(Request)`

**Comment by tmarkovski** [comment]
I would also suggest to implement this (hashing support) as a feature, for an added task challenge, but this is not required.

**Comment by fundthmcalculus** [comment]
> Yeah, I'm leaning towards a separate API. I would use the type prefix at the start `blake3_hash`, `blake3_keyed_hash`, `blake3_derive_key` and their message types accordingly `Blake3HashRequst`, etc.
> 
> This, combined with the namespace, makes it unambigous - `okapi/hashing/v1/blake3_hash(Request)`

I approve. Let's do it this way. Makes everything unambiguous and easy to access. If we need some utility function of "hash by 3 algorithms given", we can handle that at the API layer.
