### ISSUE TITLE
Expose SHA256 api

### ISSUE THREAD

**Issue by fundthmcalculus** [trinsic-id/okapi#357]
Expose the new SHA256 FFI call.

Languages:
- [x] .NET
- [x] Go
- [x] Java
- [x] Node
- [x] Python
- [x] Ruby
- [x] Swift
- [x] Wasm

**Comment by tmarkovski** [comment]
Are these waiting for me to tend to them?

**Comment by fundthmcalculus** [comment]
I got them. Setting my okapi node environment up.
