### ISSUE TITLE
Make Language bindings verify the version of okapi binaries they are loading

### ISSUE THREAD

**Issue by fundthmcalculus** [trinsic-id/okapi#374]
We should verify that the okapi native binaries we are loading are matched to a given version of the language wrapper. This prevents issues where the wrapper tries to call native FFI functions that don't exist (or have changed).

Languages:
- [x] ~.NET~ (includes native binaries in nuget)
- [x] ~Go~ (compiles on user machine, CGO will find the issue)
- [x] ~Java~ (we could package into the jar) - android requires it to be separate anyway, and Java has the most flexible path loader
- [x] ~Node~ (includes native binaries in npm)
- [x] Python (we could include the native binaries in pypi?) - https://github.com/trinsic-id/okapi/pull/376
- [x] Ruby (we could include the native binaries in the rubygem?) - https://github.com/trinsic-id/okapi/pull/375
- [x] ~Swift~ (compiles on user machine, swift will find it)
- [x] ~Wasm~ (included binary, no work needed)

**Comment by tmarkovski** [comment]
I think we should do this in CI, to ensure we build and test against the same version. For languages that require separate pre-install step of the static libraries, it's fine if we rely on the developer to install the same version. For example:

```
// install native library
brew install okapi -v 1.3.0
dpkg install okapi-1.3.0.dpkg

pip install okapi -v 1.3.0
//or
go get okapi@1.3.0
```

Another option is to add version function in Okapi `get_version()` and ensure the wrapper checks for that, but I don't think that's needed at this point.
We should maintain good SDK documentation when it comes to instructions for installing native libraries, that points to a specific versions, rather than latest, unless we match okapi and sdk versions, which we said we wouldn't.

**Comment by fundthmcalculus** [comment]
> I think we should do this in CI, to ensure we build and test against the same version. For languages that require separate pre-install step of the static libraries, it's fine if we rely on the developer to install the same version. For example:

I have a tweak in place to specify the run version so that we're building and testing the sdk's against a known good okapi binary (pre 1.4.0). That being sad, my proposal is to *eliminate* the need for the CI pipeline to download the binaries separately by including them in pypi and rubygems. If we're going to include the native binaries with the language wrapper for one thing, we should do it for everything, if possible.
 
> Another option is to add version function in Okapi `get_version()` and ensure the wrapper checks for that, but I don't think that's needed at this point.

If we're going to have hard version dependencies, we probably should have this requirement. It would allow the language wrappers to give better errors about "version not supported, please install the correct version [link to documentation]" over just a 401 unauthorized when trying to access the SDK.

> We should maintain good SDK documentation when it comes to instructions for installing native libraries, that points to a specific versions, rather than latest, unless we match okapi and sdk versions, which we said we wouldn't.

We shouldn't match okapi and sdk versions, although 1.4.0 and ecosystems kind of are making a hard link - at least this time.

**Comment by fundthmcalculus** [comment]
For go, we could simply have a `go run download_binaries.go` script similar to this: https://gist.github.com/msoap/a9ee054f80a58b16867c . From there, we can `go build` the entire package as expected. If the user is building against go, I figure it is safe to assume that they have go properly installed and configured on their machine.
