### ISSUE TITLE
Proposed DIDComm test for https://github.com/trinsic-id/okapi/tree/main/dotnet/Tests/Okapi.Tests fails

### ISSUE THREAD

**Issue by mwherman2000** [trinsic-id/okapi#392]
Add DIDComm tests to `https://github.com/trinsic-id/okapi/tree/main/dotnet/Tests/Okapi.Tests`; more specifically test cases for `DIDComm.Pack()` and `DIDComm.Unpack()`.

The main reason I'm asking is because I have some sample code that I'm trying to make work against a fresh build of the `https://github.com/trinsic-id/okapi/tree/main/dotnet/Library/Okapi` library and my `Unpack()` is failing trying to make the native call to the unpack function.

Languages:
- [x] .NET

**Comment by mwherman2000** [comment]
Here's a 3 line test in my fork integrated into the original project's Xunit Test harness:

https://github.com/mwherman2000/okapi/blob/main/dotnet/Tests/Okapi.Tests/DIDComTests.cs

I can PR this once we figure out why it's failing.

**Comment by mwherman2000** [comment]
Failed test...
![image](https://user-images.githubusercontent.com/6101736/161668386-56afec92-78c4-4df8-aaa7-e51bc7824531.png)

**Comment by mwherman2000** [comment]
Running `winget install okapi` didn't change anything.

**Comment by fundthmcalculus** [comment]
Is this an SDK change, or a bug report? I'm asking because I need to know if it's applicable to every language, or just .NET.

**Comment by mwherman2000** [comment]
@fundthmcalculus Bug report.  The TestPack() test I added to me fork fails accessing a native library (I think).  I believe it's a bug in the Okapi library.  To make the bug easy to reproduce, I coded up the repo as a test case.

**Comment by fundthmcalculus** [comment]
> Running `winget install okapi` didn't change anything.

Let me investigate this too.

**Comment by fundthmcalculus** [comment]
> @fundthmcalculus Bug report. The TestPack() test I added to my fork fails accessing a native library (I think). I believe it's a bug in the Okapi library (or perhaps `Initialize.ps1` is missing a library or the wrong version of a library or something like that). To make the bug easy to reproduce, I coded up the repo as a test case.

Pulled in the provided test case. The error you receive is a native-code error, meaning that it is executing the call from .NET into the native rust library, and failing inside that. "Failed to execute function" is a misnomer. I am investigating why this test (and thus the associated sample in `okapi-examples`) fails.

**Comment by fundthmcalculus** [comment]
Specify the encryption mode as follows: `{ Plaintext = message.ToByteString(), SenderKey = Alice.SecretKey, ReceiverKey = Bob.PublicKey, Mode = EncryptionMode.Direct });` and the test should pass. I will add this test (and example to the relevant repositories).

**Comment by mwherman2000** [comment]
@fundthmcalculus Thank you!
