### ISSUE TITLE
Golang library path search

### ISSUE THREAD

**Issue by sethjback** [trinsic-id/okapi#437]
The native call code for golang makes a couple of assumptions about *nix systems that may not hold true and cause some friction when using the library.

In the following:

https://github.com/trinsic-id/okapi/blob/ff1c7a2afd50bde7d4e7e6d4c9a737e212c36e42/go/okapi/native.go#L60-L80

The `LD_LIBRARY_PATH` envar is not always going to be set, so what you may end up with is simply looking in the directory "." for the shared library. If that is the case, and since this check happens at run time, you end up always having to have the `libokapi.so` library in whatever path you are calling the binary from.

The problem could potentially be avoided by doing a static build (I am running into some problems there and will open a new ticket), but that may not always be ideal.

Essentially the above short-circuits the system configured dynamic linker which will cause issues unless the share okapi library is placed in exactly the correct location at runtime or the `LD_LIBRARY_PATH` is set. If this is expected behavior we should update the documentation.

**Comment by fundthmcalculus** [comment]
We actually used to have a static build, but decided to eliminate it due to the additional complexity it produced. We could easily change the path that we use to search. I've wondered abourt switching to a `TRINSIC_LIBRARY_PATH` so that we aren't reusing locations. Ideally, looking in the current directory would make sense.

**Comment by sethjback** [comment]
There is a static lib included in the zip which should work, I was referring to statically linking it in the go bin.

> I've wondered abourt switching to a `TRINSIC_LIBRARY_PATH` so that we aren't reusing locations. Ideally, looking in the current directory would make sense.

Thinking about this a little more:

1. I think it would be better to use system configured library paths rather than forcing developers to manage this. I think the issue is we are doing our own check now and panic if we can't find the libraries in paths that aren't valid for all *nix platforms. One possible solution is to just add the common `/lib` and `/usr/lib` as search locations, which would also keep the benefit of looking in `.` for the libraries

2. I like being able to just ship the libraries with the binary and put them all in the same location - we should just document that it is the path relative to called binary at **run time** - that means if you have a bin and the libraries in `/opt/myprogram/` but call it from `/opt/` the libraries would need to be in `/opt/`

3. This does feel a little like an anti-pattern. Normally I would assume you the libraries would ship with the go src code and be referenced in the cgo comments, or it would be configured to look in the configured dynamic library paths for your system.

**Comment by fundthmcalculus** [comment]
@sethjback take a look here:
https://github.com/trinsic-id/okapi/pull/446

We are now relying on the OS to provide it, or use `OKAPI_LIBRARY_PATH` as an override. Is this what you think would work?

**Comment by sethjback** [comment]
Yep - it was the panic at not finding the library that was causing the issue.
