### ISSUE TITLE
[Rust] Support additional JSON formats in response messages

### ISSUE THREAD

**Issue by tmarkovski** [trinsic-id/okapi#48]
## Problem

The response messages currently return any JSON data wrapped in a `google.protobuf.Struct` message. Some languages provide parser and formatter that can convert this message into string. However, many languages don't have this support.
Specifically, Objective C tooling doesn't have support for this and the recommended way to work with random JSON data is just to use binary or string serialization.
Additionally, users unfamiliar with Protobuf don't always know how to handle this message.

## Solution

Provide support for additional message formats by allowing the users to specify which format they would like the response to be in, for API's that return JSON format. The additional formats should be:

- Binary - a direct output of the `serde` tools in Rust
- String - UTF-8 string representation of the binary format (mostly a convenience option)

## Proposal

Let's define a new proto message. This can reside in a new proto file `common.proto`

```proto
syntax = "proto3";
package okapi.common;

enum JsonFormat {
    Protobuf = 0;
    Binary = 1;
    String = 2;
}
```

We set the default value to be `Protobuf` which corresponds to the currently used `Struct` type.

Let's take the message for generating keys. Request and response are currently defined as:

```proto
message GenerateKeyRequest {
    bytes seed = 1;
    KeyType key_type = 2;
}
message GenerateKeyResponse {
    repeated JsonWebKey key = 1;
    google.protobuf.Struct did_document = 2;
}
```

Using the newly created `JsonFormat` type, we want to update their definition to:

```proto
message GenerateKeyRequest {
    bytes seed = 1;
    KeyType key_type = 2;

    okapi.common.JsonFormat json_format = 3;
}

message GenerateKeyResponse {
    repeated JsonWebKey key = 1;
    oneof result {
        google.protobuf.Struct did_document = 2;
        bytes did_document_bytes = 3;
        string did_document_string = 4;
    }
}
```

Because we have preserved the original field numbers and types, this update is backwards compatible with a non-breaking protocol change.

Using Rust's `serde_json` crate, we can augment all API's to return the result in one of the requested formats.

The APIs that need this update are:

- DIDKey - `generate`, `resolve`
- LdProofs - `create_proof`

## Deliverable

- [ ] Updated proto messages
- [ ] Rust implementation in the existing APIs
  - [ ] DIDKey.generate
  - [ ] DIDKey.resolve
  - [ ] LdProofs.create_proof
  - [ ] Unit tests
- [ ] Update or verify non-breaking change
  - [ ] .NET wrapper
  - [ ] Wasm
  - [ ] Objective C
    - [ ] Regenerate the messages in `objc/Generated` to ensure the new formats become part of the Pod

**Comment by fundthmcalculus** [comment]
Python also doesn't like the `Struct()` format. It would MUCH prefer a JSON serialized variant.

**Comment by fundthmcalculus** [comment]
@tmarkovski  is this a priority anymore if we are switching to JSON strings for everything?

**Comment by tmarkovski** [comment]
No. As we spoke today, I'd be happy to remove all complexity in the proto contracts with JSON and just use string format across the board.

**Comment by fundthmcalculus** [comment]
I'm completely in support of that, let's plan to do that soon. It's easy
for me to make the okapi layer changes in various languages.
