### ISSUE TITLE
Support for did:peer?

### ISSUE THREAD

**Issue by mwherman2000** [trinsic-id/okapi#586]
Any plans to support did:peer in OKAPI? This is becoming very important in the DIDComm world for out-of-band invitations.

Languages:
- [ ] .NET
- [ ] Go
- [ ] Java
- [ ] Dart
- [ ] Python
- [ ] Swift
- [ ] Wasm

**Comment by fundthmcalculus** [comment]
There are no plans on the road map at present, but I will confer with my teammates and see what plans could be made. Will let you know what I find out.

@tmarkovski @chiarapaskulin @janpieterz

**Comment by mwherman2000** [comment]
Is there a future roadmap for OKAPI?
