### ISSUE TITLE
Is Trinsic planning to be part of the IIW36 DIDComm interoperability testing in April 2023?

### ISSUE THREAD

**Issue by mwherman2000** [trinsic-id/okapi#587]
Is Trinsic planning to be part of the IIW36 DIDComm interoperability testing in April 2023?

Languages:
- [ ] .NET
- [ ] Go
- [ ] Java
- [ ] Dart
- [ ] Python
- [ ] Swift
- [ ] Wasm

**Comment by fundthmcalculus** [comment]
@tmarkovski thoughts?
